volumes:
  mysql:

services:
  mysql:
    image: 'mysql:5.7'
    working_dir: /application
    volumes:
      - '.:/application'
      - 'mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vendas
      - MYSQL_USER=vendas
      - MYSQL_PASSWORD=vendas
    ports:
      - '8333:3306'

  webserver:
    image: 'nginx:alpine'
    working_dir: /application
    volumes:
      - '.:/application'
      - './.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8003:80'

  php-fpm:
    image: felipemjesus/php:7.4-fpm
    working_dir: /application
    volumes:
      - '.:/application'
      - './.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'

  frontend:
    image: "node:18"
    working_dir: /home/node/app
    volumes:
      - './resources/vue:/home/node/app'
    environment:
      NODE_ENV: development
    ports:
      - '8000:8000'
    command: "npm run serve"
    entrypoint: /home/node/app/entrypoint.sh
