name: Homologation

on:
  workflow_dispatch:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.1.0

      - name: Setup enviroment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Remove unnecessary files
        run: |
          rm -rf .git .github .gitattributes .gitignore .editorconfig .env.example
          rm -rf .phpstorm.meta.php .styleci.yml _ide_helper.php
          rm -rf docker-compose.yml package.json webpack.mix.js

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-dev --optimize-autoloader --no-suggest --ignore-platform-reqs --no-scripts --no-interaction

      - name: Create env file
        env:
          HOM_ENV_FILE: ${{ secrets.HOM_ENV_FILE }}
        run: |
          echo $HOM_ENV_FILE | base64 --decode > .env
          php artisan key:generate --ansi
          php artisan jwt:secret --force

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.HOM_KEY }}
          REMOTE_HOST: ${{ secrets.HOM_HOST }}
          REMOTE_PORT: ${{ secrets.HOM_PORT }}
          REMOTE_USER: ${{ secrets.HOM_USER }}
          SOURCE: './*'
          TARGET: '~/public_html/vendas-minisitio'

      - name: Run migrations and seeders, clear cache for views, config and routes
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ~/public_html/vendas-minisitio
            php artisan migrate
            php artisan optimize
          host: ${{ secrets.HOM_HOST }}
          port: ${{ secrets.HOM_PORT }}
          user: ${{ secrets.HOM_USER }}
          key: ${{ secrets.HOM_KEY }}
