name: Prodution

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup enviroment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Remove unnecessary files
        run: |
          rm -rf .git .github .gitattributes .gitignore .editorconfig .env.example
          rm -rf .phpstorm.meta.php .styleci.yml _ide_helper.php
          rm -rf docker-compose.yml package.json webpack.mix.js

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-dev --optimize-autoloader --no-suggest --ignore-platform-reqs --no-scripts --no-interaction

      - name: Create env file
        env:
          PROD_ENV_FILE: ${{ secrets.PROD_ENV_FILE }}
        run: |
          echo $PROD_ENV_FILE | base64 --decode > .env
          php artisan key:generate --ansi
          php artisan jwt:secret --force

      - name: Run clear cache for views, config and routes
        run:
          php artisan config:clear
          php artisan view:clear
          php artisan route:clear

      - name: Commit deploy changes
        run:
          git config user.name "Felipe Martins"
          git config user.email "felipemjesus@outlook.com"
          git add .
          git commit -m "Deploy"

      - name: Deploy to server
        uses: sebastianpopp/git-ftp-action@releases/v3
        with:
          url: ${{ secrets.PROD_FTP_HOST }}
          user: ${{ secrets.PROD_FTP_USER }}
          password: ${{ secrets.PROD_FTP_PASS }}
          options: '--auto-init --force --verbose'
