name: 🚀 Production

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v1
        with:
          ref: main

      - name: Frontend - setup enviroment
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Frontend - install dependencies and build
        run: |
          cd ./resources/vue/ && \
          npm install && \
          npm run build

      - name: Backend - setup enviroment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Backend - install dependencies
        run: composer install --prefer-dist --no-dev --optimize-autoloader --no-suggest --ignore-platform-reqs --no-scripts --no-interaction

      - name: Backend - build application
        env:
          ENV_FILE: ${{ secrets.PROD_ENV_FILE }}
        run: |
          echo $ENV_FILE | base64 --decode > .env
          php artisan key:generate --ansi
          php artisan jwt:secret --force
          php artisan config:clear
          php artisan view:clear
          php artisan route:clear

      - name: Sync files
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.PROD_GIT_FTP_URL }}
          user: ${{ secrets.PROD_FTP_USER }}
          password: ${{ secrets.PROD_FTP_PWD }}
          local_dir: "./"
          remote_dir: "/vendas"
          ftp_ssl_allow: "true"
