name: Prodution

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Build application
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      - name: Deploy to server
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.PROD_FTP_HOST }}
          user: ${{ secrets.PROD_FTP_USER }}
          password: ${{ secrets.PROD_FTP_PASS }}
          local_dir: "./dist"
          remote_dir: "./vendas/public"
          delete: "false"
